name: ET Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 仅监听标签推送事件

jobs:
  version-validation:
    name: Version Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Strict Version Check
        id: version_check
        run: |
          # 获取标签版本（自动剥离v前缀）
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          
          # 获取package.json版本
          PKG_VERSION=$(jq -r .version package.json)
          
          # 严格比较版本
          if [[ "$TAG_VERSION" != "$PKG_VERSION" ]]; then
            echo "::error::版本不匹配！标签版本: $TAG_VERSION, package.json版本: $PKG_VERSION"
            echo "请执行以下命令修复："
            echo "1. 更新package.json版本: npm version $TAG_VERSION --no-git-tag-version"
            echo "2. 重新提交并推送标签"
            exit 1
          fi
          
          echo "版本校验通过: $TAG_VERSION"

  build:
    needs: version-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run build

  publish:
    needs: [version-validation, build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}