name: Publish Unity Package

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 提取标签版本号
      - name: Set version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # 构建Unity包
      - name: Build with Unity
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows
          projectPath: ./YourProject

      # 更新package.json版本
      - name: Update package version
        run: |
          cd Build/YourPackage
          jq --arg ver "${{ env.VERSION }}" '.version = $ver' package.json > tmp.json
          mv tmp.json package.json

      # 推送至UPM分支
      - name: Push to UPM branch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/upm',
              sha: context.sha
            })